### ISSUE TITLE
Package?

### ISSUE THREAD

**Issue by charJe** [chebert/schemeish#2]
I finaly got around to trying this. I still like it a lot and am glad to see you continuing to contribute to it.

The readme says to use `:schemeish` while the package file says to use `#:SCHEMEISH.SCHEMEISH`(which actually works). One of theses needs to change (I would prefer to `:use :schemeish`.

**Comment by chebert** [comment]
wow. I'm sorry I missed these. they were drowned out in irrelevant notifications.

Yes, I agree that there should be a `:schemeish` package.
